In [179]:
import pandas as pd
import numpy as np
import scipy.sparse as sp

In [180]:
arr_test = pd.read_table("test.dat", skip_blank_lines=False, delim_whitespace=True).to_numpy()

In [181]:
arr_test

array([[   75,   653],
       [   75,  1527],
       [   75,  3258],
       ...,
       [71534,  4306],
       [71534,  7132],
       [71534, 35836]], dtype=int64)

In [182]:
arr_train = pd.read_table("train.dat", skip_blank_lines=False, delim_whitespace=True).to_numpy()

In [183]:
arr_genre = pd.read_table("movie_genres.dat", skip_blank_lines=False, delim_whitespace=True).to_numpy()

In [184]:
arr_genre

array([[1, 'Adventure'],
       [1, 'Animation'],
       [1, 'Children'],
       ...,
       [65130, 'Drama'],
       [65130, 'Romance'],
       [65133, 'Comedy']], dtype=object)

In [185]:
arr_mov_tags = pd.read_table("movie_tags.dat", skip_blank_lines=False).to_numpy()


In [186]:
arr_mov_tags

array([[    1,     7,     1],
       [    1,    13,     3],
       [    1,    25,     3],
       ...,
       [65126,  5281,     1],
       [65126, 13168,     1],
       [65130,  2924,     1]], dtype=int64)

In [187]:
arr_actor = pd.read_table("movie_actors.dat", skip_blank_lines=False, encoding='latin-1').to_numpy()

In [188]:
arr_actor

array([[1, 'annie_potts', 'Annie Potts', 10],
       [1, 'bill_farmer', 'Bill Farmer', 20],
       [1, 'don_rickles', 'Don Rickles', 3],
       ...,
       [65133, 'stephen_fry', 'Stephen Fry', 8],
       [65133, 'tim_mcinnerny', 'Tim McInnerny', 9],
       [65133, 'tony_robinson', 'Tony Robinson', 10]], dtype=object)

In [189]:
arr_actor = np.delete(arr_actor, 2, 1)


In [190]:
arr_actor

array([[1, 'annie_potts', 10],
       [1, 'bill_farmer', 20],
       [1, 'don_rickles', 3],
       ...,
       [65133, 'stephen_fry', 8],
       [65133, 'tim_mcinnerny', 9],
       [65133, 'tony_robinson', 10]], dtype=object)

In [191]:
arr_direct = pd.read_table("movie_directors.dat",skip_blank_lines=False,encoding='latin-1').to_numpy()[:,0:2]

In [192]:
arr_direct

array([[1, 'john_lasseter'],
       [2, 'joe_johnston'],
       [3, 'donald_petrie'],
       ...,
       [65126, 'clark_gregg'],
       [65130, 'sam_mendes'],
       [65133, 'paul_weiland']], dtype=object)

In [193]:
import itertools as it
import warnings
warnings.filterwarnings("ignore")

In [194]:
arr_train

array([[7.5000e+01, 3.0000e+00, 1.0000e+00],
       [7.5000e+01, 3.2000e+01, 4.5000e+00],
       [7.5000e+01, 1.1000e+02, 4.0000e+00],
       ...,
       [7.1534e+04, 4.6578e+04, 4.0000e+00],
       [7.1534e+04, 6.1075e+04, 5.0000e+00],
       [7.1534e+04, 6.2049e+04, 4.5000e+00]])

In [195]:
arr_user = np.unique(np.concatenate((arr_train[:,0], arr_test[:,0])))

In [196]:
arr_user

array([   75.,    78.,   127., ..., 71525., 71529., 71534.])

In [197]:
arr_user = dict(zip(arr_user, np.arange(arr_user.size))) 

In [198]:
arr_user

{75.0: 0,
 78.0: 1,
 127.0: 2,
 170.0: 3,
 175.0: 4,
 190.0: 5,
 267.0: 6,
 325.0: 7,
 383.0: 8,
 476.0: 9,
 477.0: 10,
 493.0: 11,
 498.0: 12,
 533.0: 13,
 545.0: 14,
 548.0: 15,
 580.0: 16,
 622.0: 17,
 636.0: 18,
 637.0: 19,
 728.0: 20,
 732.0: 21,
 783.0: 22,
 788.0: 23,
 894.0: 24,
 922.0: 25,
 937.0: 26,
 1017.0: 27,
 1035.0: 28,
 1047.0: 29,
 1117.0: 30,
 1118.0: 31,
 1122.0: 32,
 1160.0: 33,
 1164.0: 34,
 1174.0: 35,
 1198.0: 36,
 1224.0: 37,
 1225.0: 38,
 1267.0: 39,
 1278.0: 40,
 1282.0: 41,
 1355.0: 42,
 1392.0: 43,
 1436.0: 44,
 1496.0: 45,
 1504.0: 46,
 1510.0: 47,
 1547.0: 48,
 1600.0: 49,
 1632.0: 50,
 1652.0: 51,
 1663.0: 52,
 1713.0: 53,
 1724.0: 54,
 1728.0: 55,
 1751.0: 56,
 1860.0: 57,
 1910.0: 58,
 1915.0: 59,
 1988.0: 60,
 2039.0: 61,
 2053.0: 62,
 2102.0: 63,
 2108.0: 64,
 2136.0: 65,
 2200.0: 66,
 2204.0: 67,
 2218.0: 68,
 2276.0: 69,
 2315.0: 70,
 2429.0: 71,
 2435.0: 72,
 2455.0: 73,
 2471.0: 74,
 2477.0: 75,
 2513.0: 76,
 2517.0: 77,
 2556.0: 78,
 2558.0: 79,

In [199]:
movies = np.unique(np.concatenate((arr_train[:,1], arr_test[:,1], np.asarray(arr_genre[:,0], dtype=int),arr_mov_tags[:,1],
                                   np.asarray(arr_direct[:,0], dtype=int), np.asarray(arr_actor[:,0], dtype=int),)))

In [200]:
movies

array([1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 6.5126e+04, 6.5130e+04,
       6.5133e+04])

In [201]:
movies = dict(zip(movies, np.arange(movies.size)))

In [202]:
movies

{1.0: 0,
 2.0: 1,
 3.0: 2,
 4.0: 3,
 5.0: 4,
 6.0: 5,
 7.0: 6,
 8.0: 7,
 9.0: 8,
 10.0: 9,
 11.0: 10,
 12.0: 11,
 13.0: 12,
 14.0: 13,
 15.0: 14,
 16.0: 15,
 17.0: 16,
 18.0: 17,
 19.0: 18,
 20.0: 19,
 21.0: 20,
 22.0: 21,
 23.0: 22,
 24.0: 23,
 25.0: 24,
 26.0: 25,
 27.0: 26,
 28.0: 27,
 29.0: 28,
 30.0: 29,
 31.0: 30,
 32.0: 31,
 33.0: 32,
 34.0: 33,
 35.0: 34,
 36.0: 35,
 37.0: 36,
 38.0: 37,
 39.0: 38,
 40.0: 39,
 41.0: 40,
 42.0: 41,
 43.0: 42,
 44.0: 43,
 45.0: 44,
 46.0: 45,
 47.0: 46,
 48.0: 47,
 49.0: 48,
 50.0: 49,
 51.0: 50,
 52.0: 51,
 53.0: 52,
 54.0: 53,
 55.0: 54,
 56.0: 55,
 57.0: 56,
 58.0: 57,
 59.0: 58,
 60.0: 59,
 61.0: 60,
 62.0: 61,
 63.0: 62,
 64.0: 63,
 65.0: 64,
 66.0: 65,
 67.0: 66,
 68.0: 67,
 69.0: 68,
 70.0: 69,
 71.0: 70,
 72.0: 71,
 73.0: 72,
 74.0: 73,
 75.0: 74,
 76.0: 75,
 77.0: 76,
 78.0: 77,
 79.0: 78,
 80.0: 79,
 81.0: 80,
 82.0: 81,
 83.0: 82,
 84.0: 83,
 85.0: 84,
 86.0: 85,
 87.0: 86,
 88.0: 87,
 89.0: 88,
 90.0: 89,
 91.0: 90,
 92.0: 91,
 93.0: 

In [203]:
arr_genres = np.unique(arr_genre[:,1])
arr_genres = dict(zip(arr_genres, np.arange(arr_genres.size)))

In [204]:
arr_genres

{'Action': 0,
 'Adventure': 1,
 'Animation': 2,
 'Children': 3,
 'Comedy': 4,
 'Crime': 5,
 'Documentary': 6,
 'Drama': 7,
 'Fantasy': 8,
 'Film-Noir': 9,
 'Horror': 10,
 'IMAX': 11,
 'Musical': 12,
 'Mystery': 13,
 'Romance': 14,
 'Sci-Fi': 15,
 'Short': 16,
 'Thriller': 17,
 'War': 18,
 'Western': 19}

In [205]:
actors = np.unique(arr_actor[:,1])
actors = dict(zip(actors, np.arange(actors.size)))

In [206]:
actors

{'1000057-don_adams': 0,
 '10000635-joel_michaely': 1,
 '10000643-john_hensley': 2,
 '1000066-julie_adams': 3,
 '10000665-amy_acker': 4,
 '10000699-john_frazier': 5,
 '1000072-nick_adams': 6,
 '10000740-bijan_daneshmand': 7,
 '10000961-jody_hill': 8,
 '10000963-mary_jane_bostic': 9,
 '10001130-sophie_monk': 10,
 '10001274-ben_walker': 11,
 '10001332-mo_collins': 12,
 '10001389-jonathan_sadowski': 13,
 '10001403-arlen_escarpeta': 14,
 '10001428-lance_barber': 15,
 '10001487-oscar_nunez': 16,
 '10001530-claire_bloom': 17,
 '10001763-dylan_blue': 18,
 '10001785-fenella_woolgar': 19,
 '10001855-teresa_palmer': 20,
 '10001860-sam_harris': 21,
 '10002085-robin_weigert': 22,
 '10002097-travis_van_winkle': 23,
 '10002176-peter_stickles': 24,
 '10002254-masi_oka': 25,
 '10002317-tara_summers': 26,
 '10002345-gonzalo_menendez': 27,
 '10002392-jayma_mays': 28,
 '10002539-jack_carpenter': 29,
 '10002741-andre_de_toth': 30,
 '10002753-harriet_hilliard': 31,
 '10002754-claire_trevor': 32,
 '10002976

In [207]:
directors = np.unique(arr_direct[:,1])
directors = dict(zip(directors, np.arange(directors.size)))

In [208]:
directors

{'10000507-wisit_sasanatieng': 0,
 '10000961-jody_hill': 1,
 '10002677-chris_hall': 2,
 '10004245-mamoru_hosoda': 3,
 '10004810-sophie_fiennes': 4,
 '1000993-bruce_barry': 5,
 '1001257-peter_berg': 6,
 '1001975-richard_brooks': 7,
 '1006013-keith_gordon': 8,
 '1006266-paul_gross': 9,
 '1009699-bill_maher': 10,
 '1010002-tony_martin': 11,
 '1010653-david_miller': 12,
 '1013265-james_robinson': 13,
 '1013435-david_ross': 14,
 '1015315-don_taylor': 15,
 '1015742-michael_tucker': 16,
 '1022918-andrew_davis': 17,
 '1025643-steve_white': 18,
 '1028179-william_a_seiter': 19,
 '1028754-tom_kennedy': 20,
 '1028855-david_butler': 21,
 '1029950-michael_davis': 22,
 '1030366-kevin_smith': 23,
 '1031663-tim_johnson': 24,
 '1033700-henry_miller': 25,
 '1036363-james_wong': 26,
 '1036586-chris_williams': 27,
 '1036678-tom_moore': 28,
 '1040928-john_carpenter': 29,
 '1040953-nick_castle': 30,
 '1041041-larry_cohen': 31,
 '1041173-richard_day': 32,
 '1041374-james_fargo': 33,
 '1041466-richard_franklin

In [209]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from statistics import mean
from time import time, ctime
from math import ceil

In [210]:
def conversion_sparse(rec, d1=None, d2=None, boolean=False):
    data = []
    i = []
    j = []
    
    for x in rec:
        
        if d1==None:
            i.append(x[0])
        else:
            i.append(d1[x[0]])
        if d2==None:
            j.append(x[1])
        else:
            j.append(d2[x[1]])
        
        if boolean==False:
            data.append(x[2])
        else:
            data.append(1)
    return sp.coo_matrix((data, (i,j)), shape = [np.amax(i)+1, np.amax(j)+1]).tocsr()

In [211]:
arr_train = conversion_sparse(arr_train, arr_user, movies)
arr_genre = conversion_sparse(arr_genre, movies, arr_genres, boolean=True)
arr_mov_tags = conversion_sparse(arr_mov_tags, movies, None)
arr_actor = conversion_sparse(arr_actor, movies, actors)
arr_direct = conversion_sparse(arr_direct, movies, directors, boolean=True)
tfidf = TfidfTransformer()
arr_mov_tags = tfidf.fit_transform(arr_mov_tags)

In [212]:
arr_train

<2113x12329 sparse matrix of type '<class 'numpy.float64'>'
	with 641699 stored elements in Compressed Sparse Row format>

In [213]:
def item_based_filtering(train_sparse, arr_test, tags_sparse, k=175):
    test_y = []
    cos_sim_user = cosine_similarity(train_sparse, train_sparse,dense_output=False)   
    cos_sim_movie = cosine_similarity(train_sparse.transpose(), train_sparse.transpose(), dense_output=False)
    cos_sim_tag = cosine_similarity(tags_sparse, tags_sparse, dense_output=False)
    
    for index, line in enumerate(arr_test):
        user = arr_user[line[0]]
        movie = movies[line[1]]
        
        neighbor_user_ind = cos_sim_user[user].todense()
        neighbor_user_ind = np.array(neighbor_user_ind).flatten()
        neighbor_user_ind = neighbor_user_ind.argpartition(-k-1)[-k-1:]
        neighbor_user_ind = neighbor_user_ind[np.where(neighbor_user_ind != user)]
        
        user_ratings = []
        for userID in neighbor_user_ind:
            user_ratings.append(train_sparse[userID, movie])
            
        user_ratings = np.array(user_ratings)
        user_ratings = user_ratings[np.nonzero(user_ratings)]
        
        if user_ratings.size == 0:
            
            try:            
                user_rating = user_ratings.mean()
            except:
                
                user_rating = 0
        else:
            user_rating = user_ratings.mean()
            
            
        neighbor_mov_ind = cos_sim_movie[movie].todense()
        neighbor_mov_ind = np.array(neighbor_mov_ind).flatten()
        neighbor_mov_ind = neighbor_mov_ind.argpartition(-k-1)[-k-1:]
        neighbor_mov_ind = neighbor_mov_ind[np.where(neighbor_mov_ind != movie)]
        movie_ratings = []
        
        for movieID in neighbor_mov_ind:
            movie_ratings.append(train_sparse[user, movieID])
            
        movie_ratings = np.array(movie_ratings)
        movie_ratings = movie_ratings[np.nonzero(movie_ratings)]
        
        
        if movie_ratings.size == 0:
            movie_ratings = train_sparse[:, movie].data 
            movie_rating = movie_ratings.mean()
            
            if (np.isnan(movie_rating)): 
                movie_rating = 0
        else:
            movie_rating = movie_ratings.mean()
            
            
        tag_neighbor_indices = cos_sim_tag[movie].todense()
        tag_neighbor_indices = np.array(tag_neighbor_indices).flatten()
        tag_neighbor_indices = tag_neighbor_indices.argpartition(-k-1)[-k-1:]
        tag_neighbor_indices = tag_neighbor_indices[np.where(tag_neighbor_indices != movie)]
        
        new_ratings = train_sparse[:, tag_neighbor_indices]
        tag_ratings = np.true_divide(new_ratings.sum(0),(new_ratings!=0).sum(0))
        
        tag_rating = np.nanmean(tag_ratings)
        
        ratings = np.array([user_rating, movie_rating, tag_rating])
        
        ratings = ratings[np.nonzero(ratings)]
 
       
        if ratings.size == 0:
            new_rating = 3.0
        else:
            new_rating = np.mean(ratings)
            
        
        test_y.append(new_rating)

        
        if np.isnan(new_rating):
            print(index)
            print(ratings)
        
        
        if(index % 1000 == 0):
            print(ratings)
            print(index)
            print(ctime())
        
    return np.array(test_y)

In [214]:
submission = item_based_filtering(arr_train, arr_test, arr_mov_tags, k=175)

[3.18292683 3.72727273 3.42988795]
0
Tue Nov  9 22:36:17 2021
41
[       nan 3.83333333 3.22862299]
204
[       nan 0.5        3.45725337]
264
[       nan 2.75       3.20355762]
347
[       nan 3.7        3.20355762]
438
[       nan 2.25       3.18573358]
556
[      nan 2.75      3.0997446]
557
[       nan 3.5        3.20355762]
632
[       nan 3.5        3.18573358]
859
[       nan 3.21875    3.48642938]
970
[       nan 3.5        2.85057983]
981
[       nan 2.83333333 3.21499371]
[3.97142857 4.1984127  3.70034571]
1000
Tue Nov  9 22:36:27 2021
1043
[       nan 4.         3.19953624]
1166
[       nan 2.6875     3.24020781]
1262
[      nan 3.375     3.1910936]
1438
[       nan 2.41666667 3.20355762]
1497
[       nan 3.5        3.24898561]
1559
[       nan 3.5047619  3.20355762]
1814
[       nan 3.35       3.18517244]
[3.24074074 3.34705882 3.17042432]
2000
Tue Nov  9 22:36:36 2021
2014
[       nan 2.11538462 3.20355762]
2287
[       nan 3.5        3.28536726]
2356
[       nan 2.375    

In [215]:
np.savetxt('out4.dat', submission, fmt='%s')

In [216]:
recc = pd.read_table("out4.dat", skip_blank_lines=False, delim_whitespace=True, header = None)

In [217]:
recc

0
0      3.446696
1      3.697433
2      2.958532
3      3.685935
4      3.674838
...         ...
71294  4.076619
71295  3.875550
71296  3.536929
71297  4.278059
71298  3.511013

[71299 rows x 1 columns]

In [218]:
recc[0].isnull().sum()


649

In [219]:
recc[0] = recc[0].fillna(0)

In [220]:
recc[0].isnull().sum()

0

In [221]:
np.savetxt('out_final2.dat', recc, fmt='%s')